/**
 * @fileoverview gRPC-Web generated client stub for shisen_interfaces.proto3
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.1
// source: shisen.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.shisen_interfaces = {};
proto.shisen_interfaces.proto3 = require('./shisen_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.shisen_interfaces.proto3.ConfigClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.shisen_interfaces.proto3.ConfigPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.shisen_interfaces.proto3.Empty,
 *   !proto.shisen_interfaces.proto3.CaptureSetting>}
 */
const methodDescriptor_Config_GetCaptureSetting = new grpc.web.MethodDescriptor(
  '/shisen_interfaces.proto3.Config/GetCaptureSetting',
  grpc.web.MethodType.UNARY,
  proto.shisen_interfaces.proto3.Empty,
  proto.shisen_interfaces.proto3.CaptureSetting,
  /**
   * @param {!proto.shisen_interfaces.proto3.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.shisen_interfaces.proto3.CaptureSetting.deserializeBinary
);


/**
 * @param {!proto.shisen_interfaces.proto3.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.shisen_interfaces.proto3.CaptureSetting)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.shisen_interfaces.proto3.CaptureSetting>|undefined}
 *     The XHR Node Readable Stream
 */
proto.shisen_interfaces.proto3.ConfigClient.prototype.getCaptureSetting =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/GetCaptureSetting',
      request,
      metadata || {},
      methodDescriptor_Config_GetCaptureSetting,
      callback);
};


/**
 * @param {!proto.shisen_interfaces.proto3.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.shisen_interfaces.proto3.CaptureSetting>}
 *     Promise that resolves to the response
 */
proto.shisen_interfaces.proto3.ConfigPromiseClient.prototype.getCaptureSetting =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/GetCaptureSetting',
      request,
      metadata || {},
      methodDescriptor_Config_GetCaptureSetting);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.shisen_interfaces.proto3.CaptureSetting,
 *   !proto.shisen_interfaces.proto3.Empty>}
 */
const methodDescriptor_Config_SaveCaptureSetting = new grpc.web.MethodDescriptor(
  '/shisen_interfaces.proto3.Config/SaveCaptureSetting',
  grpc.web.MethodType.UNARY,
  proto.shisen_interfaces.proto3.CaptureSetting,
  proto.shisen_interfaces.proto3.Empty,
  /**
   * @param {!proto.shisen_interfaces.proto3.CaptureSetting} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.shisen_interfaces.proto3.Empty.deserializeBinary
);


/**
 * @param {!proto.shisen_interfaces.proto3.CaptureSetting} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.shisen_interfaces.proto3.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.shisen_interfaces.proto3.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.shisen_interfaces.proto3.ConfigClient.prototype.saveCaptureSetting =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/SaveCaptureSetting',
      request,
      metadata || {},
      methodDescriptor_Config_SaveCaptureSetting,
      callback);
};


/**
 * @param {!proto.shisen_interfaces.proto3.CaptureSetting} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.shisen_interfaces.proto3.Empty>}
 *     Promise that resolves to the response
 */
proto.shisen_interfaces.proto3.ConfigPromiseClient.prototype.saveCaptureSetting =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/SaveCaptureSetting',
      request,
      metadata || {},
      methodDescriptor_Config_SaveCaptureSetting);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.shisen_interfaces.proto3.CaptureSetting,
 *   !proto.shisen_interfaces.proto3.Empty>}
 */
const methodDescriptor_Config_SetCaptureSetting = new grpc.web.MethodDescriptor(
  '/shisen_interfaces.proto3.Config/SetCaptureSetting',
  grpc.web.MethodType.UNARY,
  proto.shisen_interfaces.proto3.CaptureSetting,
  proto.shisen_interfaces.proto3.Empty,
  /**
   * @param {!proto.shisen_interfaces.proto3.CaptureSetting} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.shisen_interfaces.proto3.Empty.deserializeBinary
);


/**
 * @param {!proto.shisen_interfaces.proto3.CaptureSetting} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.shisen_interfaces.proto3.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.shisen_interfaces.proto3.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.shisen_interfaces.proto3.ConfigClient.prototype.setCaptureSetting =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/SetCaptureSetting',
      request,
      metadata || {},
      methodDescriptor_Config_SetCaptureSetting,
      callback);
};


/**
 * @param {!proto.shisen_interfaces.proto3.CaptureSetting} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.shisen_interfaces.proto3.Empty>}
 *     Promise that resolves to the response
 */
proto.shisen_interfaces.proto3.ConfigPromiseClient.prototype.setCaptureSetting =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/SetCaptureSetting',
      request,
      metadata || {},
      methodDescriptor_Config_SetCaptureSetting);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.shisen_interfaces.proto3.Empty,
 *   !proto.shisen_interfaces.proto3.Image>}
 */
const methodDescriptor_Config_GetImage = new grpc.web.MethodDescriptor(
  '/shisen_interfaces.proto3.Config/GetImage',
  grpc.web.MethodType.UNARY,
  proto.shisen_interfaces.proto3.Empty,
  proto.shisen_interfaces.proto3.Image,
  /**
   * @param {!proto.shisen_interfaces.proto3.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.shisen_interfaces.proto3.Image.deserializeBinary
);


/**
 * @param {!proto.shisen_interfaces.proto3.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.shisen_interfaces.proto3.Image)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.shisen_interfaces.proto3.Image>|undefined}
 *     The XHR Node Readable Stream
 */
proto.shisen_interfaces.proto3.ConfigClient.prototype.getImage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/GetImage',
      request,
      metadata || {},
      methodDescriptor_Config_GetImage,
      callback);
};


/**
 * @param {!proto.shisen_interfaces.proto3.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.shisen_interfaces.proto3.Image>}
 *     Promise that resolves to the response
 */
proto.shisen_interfaces.proto3.ConfigPromiseClient.prototype.getImage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/shisen_interfaces.proto3.Config/GetImage',
      request,
      metadata || {},
      methodDescriptor_Config_GetImage);
};


module.exports = proto.shisen_interfaces.proto3;

